name: Check Markdown links
on:
  pull_request:
    paths:
      - '**.md'
permissions:
  contents: read

jobs:
  lint-md:
    runs-on: ubuntu-latest
    if: github.repository == 'DefinitelyTyped/DefinitelyTyped'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--filter, ., --filter, '{./scripts}...']
      - run: pnpm remark --frail . .github
